### ISSUE TITLE
Bug: Multiple Issues with tests for ES6: Create Strings using Template Literals

### ISSUE THREAD

**Issue by johnkennedy9147** [freeCodeCamp/curriculum#135]
**Describe the bug**
Text for first test should be amended to say array rather than list as this is both what we specify and test for.

Second test only passes if you use double quotes around class attribute

The test for use of template literals has an incorrect regex. The part of the regex testing for `</li>` has not been properly escaped so `/` is being treated as end of the regex, with `l` being treated as a regex flag.

There maybe additional issues with the regex, so I will try and identify all before submitting PR to fix.

**To Reproduce**
1. [](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/create-strings-using-template-literals/)
2. Create correct solution
3. Click `Run the Tests`
4. Test fails
![image](https://user-images.githubusercontent.com/26827682/42618484-0f044c74-85ad-11e8-87a9-78881754b6d3.png)

**Expected behavior**
Test should pass

**Desktop (please complete the following information):**
Reported by multiple campers - not system specific

**Comment by scissorsneedfoodtoo** [comment]
Hi @johnkennedy9147, thank you for taking the time to report this.

You're right. Even though this challenge's regex test to detect template literals was fixed and improved recently in #90, I think there's still room for further improvement. I just did some testing, and while solutions that use push and map/forEach work fine now, hard coded solutions don't seem to work. Valid template literal strings like ``<li class="text-warning">${result.failure[0]}</li>`` would still fail because the test doesn't properly check for the period or the word after.

If you're interested, here's an updated solution that might help for your future PR:

```
{ 
  "text": "Template strings were used",
  "testString":
    "getUserInput => assert(getUserInput('index').match(/`<li \\s*class\\s*=\\s*(\"\\s*text-warning\\s*\"|'\\s*text-warning\\s*')\\s*>\\s*\\$\\s*\\{(\\s*\\w+\\s*|\\s*\\w+\\.?\\w*?\\s*\\[\\s*[\\w]+\\s*\\]\\s*)\\}\\s*<\\s*\\/li\\s*>`/g), 'Template strings were used');"
}
```

Would be good to get another pair of eyes on it, though, just to make sure all valid solutions pass. Here's a [regexr](regexr.com/3sb51) link that can help. And I'm not the best at regex, so please feel free to change or simplify the pattern as you see fit.

All that said, the second test still needs to be updated to support single quotes like you mentioned. Looking forward to your upcoming PR!

**Comment by SandySingh** [comment]
@scissorsneedfoodtoo Solution using map is still not working.

**Comment by hnryjmes** [comment]
@scissorsneedfoodtoo can I confirm whether there is any way to pass the test in its current state, or whether we need to wait for a site refresh?

**Comment by johnkennedy9147** [comment]
#140 fixed incorrect text in first test

**Comment by johnkennedy9147** [comment]
missing escaping for `/li>` fixed in  #90

**Comment by johnkennedy9147** [comment]
@scissorsneedfoodtoo I was working on the regex and it occurred to me, we have a test that checks the content and then another that checks template literals were used, that being the case in the third test do we really need a complex regex - if we are only testing for template literals then we can just do ``^`.*`$``

**Comment by scissorsneedfoodtoo** [comment]
@johnkennedy9147, just saw your PR. Great catch there! In all our work with the third test more flexible we never updated the second to accept single quotes.

About the new regex for the third test, that seems like a great idea. A simple check like that would allow all solutions I can think of to pass, and the current test doesn't have to be so complex since there's another that checks the contents of resultDisplayArray already. The only possible hangup I can think of is that the commented out code might cause the test to pass without the user actually using template literals in their code, though I'm sure that can be handled in regex, too.

**Comment by johnkennedy9147** [comment]
@scissorsneedfoodtoo unfortunately the comment is causing the test to pass. the style of test being used looks at the whole content of the code editor, and the style used in test 2 wont work as the strings being tested dont include the quote or backtick to check against.  So looks like it will have to be a big horrible regex - think I have a working solution, slightly adapted from your suggestion. Will test it properly tomorrow and raise PR.

**Comment by scissorsneedfoodtoo** [comment]
@johnkennedy9147, that's too bad. Would be great to simplify here if we could, but it's not a big deal. I was playing with the simplified regex and found something that works, though it relies on a negative lookbehind which isn't supported in Firefox yet.

Looking forward to your PR!
